function (is_alive x y out)
    list(LENGTH ARGN count)
    if(${count} EQUAL 0)
        set(${out} False PARENT_SCOPE)
        return()
    endif()
    
    math(EXPR count "${count}-1")
    foreach(i RANGE 0 ${count} 2)
        list(GET ARGN ${i} xx)
        math(EXPR i "${i}+1")
        list(GET ARGN ${i} yy)
        if ("${x};${y}" STREQUAL "${xx};${yy}")
            set(${out} True PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${out} False PARENT_SCOPE)
endfunction()

set(neighbours 
    -1;-1  0;-1  1;-1
    -1;0         1;0
    -1;1   0;1   1;1 )

function(count_living_neighbours x y output)
    set(sum 0)
    foreach(i RANGE 0 15 2)
        list(GET neighbours ${i} dx)
        math(EXPR xx "${x}+${dx}")
        math(EXPR i "${i}+1")
        list(GET neighbours ${i} dy)
        math(EXPR yy "${y}+${dy}")
        is_alive(${xx} ${yy} bval ${ARGN})
        if(bval)
            math(EXPR sum "${sum}+1")
        endif()
    endforeach()
    set(${output} ${sum} PARENT_SCOPE)
endfunction()

function(evolve result)
    set(output)
    list(LENGTH ARGN count)
    math(EXPR count "${count}-1")
    foreach(i RANGE 0 ${count} 2)
        list(GET ARGN ${i} x)
        math(EXPR i "${i}+1")
        list(GET ARGN ${i} y)
        count_living_neighbours(${x} ${y} num_of_neighbours ${ARGN})
        if ((num_of_neighbours EQUAL 2) OR (num_of_neighbours EQUAL 3))
            set(output ${output} ${x} ${y})
        endif()
        foreach(i RANGE 0 15 2)
            list(GET neighbours ${i} dx)
            math(EXPR xx "${x}+${dx}")
            math(EXPR i "${i}+1")
            list(GET neighbours ${i} dy)
            math(EXPR yy "${y}+${dy}")
            is_alive(${xx} ${yy} bval ${ARGN})
            if(NOT bval)
                count_living_neighbours(${xx} ${yy} num_of_neighbours2 ${ARGN})
                if(num_of_neighbours2 EQUAL 3)
                    set(output ${output} ${xx} ${yy})
                endif()
            endif()
        endforeach()
    endforeach()
    set(${result} ${output} PARENT_SCOPE)
endfunction()

